apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-jwks-proxy.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-jwks-proxy.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: system:service-account-issuer-discovery
  apiGroup: rbac.authorization.k8s.io
