name: Release Proxy & Helm Chart

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v1.0.0

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/k8s-jwks-proxy
  CHART_NAME: k8s-jwks-proxy

jobs:

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

    - name: Build and push image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

  helm:
    name: Package & Push Helm Chart to GHCR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: k8s-jwks-proxy
          charts_url: https://gawsoftpl.github.io/k8s-jwks-proxy
          owner: gawsoftpl
          repository: k8s-jwks-proxy
          branch: gh-pages
          target_dir: .

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [docker, helm]

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
