name: Release Proxy & Helm Chart

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v1.0.0

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/k8s-jwks-proxy
  CHART_NAME: k8s-jwks-proxy

jobs:

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

    - name: Build and push image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

  helm:
    name: Package & Push Helm Chart to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to push to gh-pages branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # fetch all history for tags if needed

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0

    - name: Package Helm chart
      run: |
        mkdir -p charts-packaged
        helm package charts/k8s-jwks-proxy --destination charts-packaged

    - name: Update Helm repo index
      run: |
        helm repo index charts-packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./charts-packaged
        publish_branch: gh-pages
        # Set this if your pages are served from root:
        # destination_dir: .

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [docker, helm]

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
